// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

export function OpenFile(): Promise<string> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3934454824) as any;
    return $resultPromise;
}

export function SaveFile(text: string): Promise<string> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1363079525, text) as any;
    return $resultPromise;
}
