// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Create as $Create} from "@wailsio/runtime";

export class ProxyConfig {
    "UpstreamPort": number;
    "DownstreamURL": string;

    /** Creates a new ProxyConfig instance. */
    constructor($$source: Partial<ProxyConfig> = {}) {
        if (!("UpstreamPort" in $$source)) {
            this["UpstreamPort"] = 0;
        }
        if (!("DownstreamURL" in $$source)) {
            this["DownstreamURL"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProxyConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): ProxyConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProxyConfig($$parsedSource as Partial<ProxyConfig>);
    }
}
